package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/account?access_token=79D451B9-26E6-6943-BDA6-AC9D05EE563DA640C336-0F50-4875-8350-23E6C642A0F1
 */
public class Account extends JsonModelFactoryMaster {

	private Integer world;

	private String access;

	private Boolean commander;

	private Integer fractalLevel;

	private List<String> guilds;

	private String created;

	private Integer monthlyAp;

	private String name;

	private Integer wvwRank;

	private String id;

	private Integer dailyAp;

	//Getters and setters

	public Integer getWorld() {
		return this.world;
	}

	public void setWorld(Integer val) {
		this.world = val;
	}

	public String getAccess() {
		return this.access;
	}

	public void setAccess(String val) {
		this.access = val;
	}

	public Boolean getCommander() {
		return this.commander;
	}

	public void setCommander(Boolean val) {
		this.commander = val;
	}

	public Integer getFractalLevel() {
		return this.fractalLevel;
	}

	public void setFractalLevel(Integer val) {
		this.fractalLevel = val;
	}

	public List<String> getGuilds() {
		return this.guilds;
	}

	public void setGuilds(List<String> val) {
		this.guilds = val;
	}

	public String getCreated() {
		return this.created;
	}

	public void setCreated(String val) {
		this.created = val;
	}

	public Integer getMonthlyAp() {
		return this.monthlyAp;
	}

	public void setMonthlyAp(Integer val) {
		this.monthlyAp = val;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String val) {
		this.name = val;
	}

	public Integer getWvwRank() {
		return this.wvwRank;
	}

	public void setWvwRank(Integer val) {
		this.wvwRank = val;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String val) {
		this.id = val;
	}

	public Integer getDailyAp() {
		return this.dailyAp;
	}

	public void setDailyAp(Integer val) {
		this.dailyAp = val;
	}

	public Account() {
		this.guilds = new ArrayList<String>();
	}

}
