package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class AccountBank extends JsonModelFactoryMaster {

	private List<Integer> infusions;

	private Integer count;

	private String binding;

	private Integer id;

	//Getters and setters

	public List<Integer> getInfusions() {
		return this.infusions;
	}

	public void setInfusions(List<Integer> val) {
		this.infusions = val;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer val) {
		this.count = val;
	}

	public String getBinding() {
		return this.binding;
	}

	public void setBinding(String val) {
		this.binding = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public AccountBank() {
		this.infusions = new ArrayList<Integer>();
	}

}
