package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class AccountInventory extends JsonModelFactoryMaster {

	private Integer count;

	private String binding;

	private Integer id;

	//Getters and setters

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer val) {
		this.count = val;
	}

	public String getBinding() {
		return this.binding;
	}

	public void setBinding(String val) {
		this.binding = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public AccountInventory() {
	}

}
