package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class AchievementTiers extends JsonModelFactoryMaster {

	private Integer count;

	private Integer points;

	//Getters and setters

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer val) {
		this.count = val;
	}

	public Integer getPoints() {
		return this.points;
	}

	public void setPoints(Integer val) {
		this.points = val;
	}

	public AchievementTiers() {
	}

}
