package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CharacterEquipmentEquipmentStatsAttributes extends JsonModelFactoryMaster {

	private Integer Precision;

	private Integer CritDamage;

	private Integer Power;

	//Getters and setters

	public Integer getPrecision() {
		return this.Precision;
	}

	public void setPrecision(Integer val) {
		this.Precision = val;
	}

	public Integer getCritDamage() {
		return this.CritDamage;
	}

	public void setCritDamage(Integer val) {
		this.CritDamage = val;
	}

	public Integer getPower() {
		return this.Power;
	}

	public void setPower(Integer val) {
		this.Power = val;
	}

	public CharacterEquipmentEquipmentStatsAttributes() {
	}

}
