package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/characters/Aliron%20Rapidblade/core?access_token=79D451B9-26E6-6943-BDA6-AC9D05EE563DA640C336-0F50-4875-8350-23E6C642A0F1
 */
public class CharacterCore extends JsonModelFactoryMaster {

	private String profession;

	private String guild;

	private String race;

	private String gender;

	private Integer level;

	private String created;

	private String name;

	private Integer title;

	private Integer age;

	private Integer deaths;

	//Getters and setters

	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String val) {
		this.profession = val;
	}

	public String getGuild() {
		return this.guild;
	}

	public void setGuild(String val) {
		this.guild = val;
	}

	public String getRace() {
		return this.race;
	}

	public void setRace(String val) {
		this.race = val;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String val) {
		this.gender = val;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer val) {
		this.level = val;
	}

	public String getCreated() {
		return this.created;
	}

	public void setCreated(String val) {
		this.created = val;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String val) {
		this.name = val;
	}

	public Integer getTitle() {
		return this.title;
	}

	public void setTitle(Integer val) {
		this.title = val;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer val) {
		this.age = val;
	}

	public Integer getDeaths() {
		return this.deaths;
	}

	public void setDeaths(Integer val) {
		this.deaths = val;
	}

	public CharacterCore() {
	}

}
