package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/commerce/listings/1178
 */
public class CommerceListing extends JsonModelFactoryMaster {

	private List<CommerceListingBuys> buys;

	private List<CommerceListingSells> sells;

	private Integer id;

	//Getters and setters

	public List<CommerceListingBuys> getBuys() {
		return this.buys;
	}

	public void setBuys(List<CommerceListingBuys> val) {
		this.buys = val;
	}

	public List<CommerceListingSells> getSells() {
		return this.sells;
	}

	public void setSells(List<CommerceListingSells> val) {
		this.sells = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public CommerceListing() {
		this.buys = new ArrayList<CommerceListingBuys>();
		this.sells = new ArrayList<CommerceListingSells>();
	}

}
