package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CommerceCurrentSellTransactions extends JsonModelFactoryMaster {

	private Integer quantity;

	private Integer itemId;

	private Integer price;

	private String created;

	private Integer id;

	//Getters and setters

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer val) {
		this.quantity = val;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer val) {
		this.itemId = val;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer val) {
		this.price = val;
	}

	public String getCreated() {
		return this.created;
	}

	public void setCreated(String val) {
		this.created = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public CommerceCurrentSellTransactions() {
	}

}
