package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/commerce/prices/1178
 */
public class CommercePrice extends JsonModelFactoryMaster {

	private CommercePriceBuys buys;

	private CommercePriceSells sells;

	private Integer id;

	private Boolean whitelisted;

	//Getters and setters

	public CommercePriceBuys getBuys() {
		return this.buys;
	}

	public void setBuys(CommercePriceBuys val) {
		this.buys = val;
	}

	public CommercePriceSells getSells() {
		return this.sells;
	}

	public void setSells(CommercePriceSells val) {
		this.sells = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public Boolean getWhitelisted() {
		return this.whitelisted;
	}

	public void setWhitelisted(Boolean val) {
		this.whitelisted = val;
	}

	public CommercePrice() {
	}

}
