package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/commerce/exchange/gems?quantity=800
 */
public class CommerceExchangeGems extends JsonModelFactoryMaster {

	private Integer coinsPerGem;

	private Integer quantity;

	//Getters and setters

	public Integer getCoinsPerGem() {
		return this.coinsPerGem;
	}

	public void setCoinsPerGem(Integer val) {
		this.coinsPerGem = val;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer val) {
		this.quantity = val;
	}

	public CommerceExchangeGems() {
	}

}
