package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Array class containing all arrays from the config file.
 */
public class GeneratedJsonArrays extends JsonModelFactoryMaster {

	private List<String> wvwMatches;

	private List<String> wvwObjectives;

	private List<Integer> colors;

	private List<Integer> items;

	private List<Integer> skins;

	//Getters and setters

	public List<String> getWvwMatches() {
		return this.wvwMatches;
	}

	public void setWvwMatches(List<String> val) {
		this.wvwMatches = val;
	}

	public List<String> getWvwObjectives() {
		return this.wvwObjectives;
	}

	public void setWvwObjectives(List<String> val) {
		this.wvwObjectives = val;
	}

	public List<Integer> getColors() {
		return this.colors;
	}

	public void setColors(List<Integer> val) {
		this.colors = val;
	}

	public List<Integer> getItems() {
		return this.items;
	}

	public void setItems(List<Integer> val) {
		this.items = val;
	}

	public List<Integer> getSkins() {
		return this.skins;
	}

	public void setSkins(List<Integer> val) {
		this.skins = val;
	}

	public GeneratedJsonArrays() {
		this.wvwMatches = new ArrayList<String>();
		this.wvwObjectives = new ArrayList<String>();
		this.colors = new ArrayList<Integer>();
		this.items = new ArrayList<Integer>();
		this.skins = new ArrayList<Integer>();
	}

}
