package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Array class containing all arrays from the config file.
 */
public class GeneratedJsonArrays extends JsonModelFactoryMaster {

	private List<AccountAchievements> accountAchievements;

	private List<AccountBank> accountBank;

	private List<Integer> accountDyes;

	private List<String> accountInventory;

	private List<AccountMaterials> accountMaterials;

	private List<Integer> accountMinis;

	private List<Integer> accountSkins;

	private List<Integer> accountTitles;

	private List<AccountWallet> accountWallet;

	private List<Integer> achievements;

	private List<Integer> achievementCategories;

	private List<String> achievementGroups;

	private List<String> characters;

	private List<Integer> commerceListings;

	private List<Integer> commercePrices;

	private List<Object> commerceCurrentBuyTransactions; //TODO: GW-0003 

	private List<CommerceCurrentSellTransactions> commerceCurrentSellTransactions;

	private List<Object> commercePastBuyTransactions; //TODO: GW-0003 

	private List<Object> commercePastSellTransactions; //TODO: GW-0003 

	private List<String> pvpGames;

	private List<Integer> pvpAmulets;

	private List<String> pvpSeasons;

	private List<PvpStandings> pvpStandings;

	private List<String> wvwMatches;

	private List<String> wvwObjectives;

	private List<Integer> colors;

	private List<Integer> continents;

	private List<Integer> currencies;

	private List<Integer> emblemForegrounds;

	private List<Integer> emblemBackgrounds;

	private List<String> files;

	private List<Integer> items;

	private List<Integer> allItemStats;

	private List<String> legends;

	private List<Integer> maps;

	private List<Integer> allMaterials;

	private List<Integer> minis;

	private List<Integer> pets;

	private List<String> professions;

	private List<String> quaggans;

	private List<Integer> recipes;

	private List<Integer> skills;

	private List<Integer> skins;

	private List<Integer> specializations;

	private List<Integer> titles;

	private List<Integer> traits;

	private List<Integer> worlds;

	//Getters and setters

	public List<AccountAchievements> getAccountAchievements() {
		return this.accountAchievements;
	}

	public void setAccountAchievements(List<AccountAchievements> val) {
		this.accountAchievements = val;
	}

	public List<AccountBank> getAccountBank() {
		return this.accountBank;
	}

	public void setAccountBank(List<AccountBank> val) {
		this.accountBank = val;
	}

	public List<Integer> getAccountDyes() {
		return this.accountDyes;
	}

	public void setAccountDyes(List<Integer> val) {
		this.accountDyes = val;
	}

	public List<String> getAccountInventory() {
		return this.accountInventory;
	}

	public void setAccountInventory(List<String> val) {
		this.accountInventory = val;
	}

	public List<AccountMaterials> getAccountMaterials() {
		return this.accountMaterials;
	}

	public void setAccountMaterials(List<AccountMaterials> val) {
		this.accountMaterials = val;
	}

	public List<Integer> getAccountMinis() {
		return this.accountMinis;
	}

	public void setAccountMinis(List<Integer> val) {
		this.accountMinis = val;
	}

	public List<Integer> getAccountSkins() {
		return this.accountSkins;
	}

	public void setAccountSkins(List<Integer> val) {
		this.accountSkins = val;
	}

	public List<Integer> getAccountTitles() {
		return this.accountTitles;
	}

	public void setAccountTitles(List<Integer> val) {
		this.accountTitles = val;
	}

	public List<AccountWallet> getAccountWallet() {
		return this.accountWallet;
	}

	public void setAccountWallet(List<AccountWallet> val) {
		this.accountWallet = val;
	}

	public List<Integer> getAchievements() {
		return this.achievements;
	}

	public void setAchievements(List<Integer> val) {
		this.achievements = val;
	}

	public List<Integer> getAchievementCategories() {
		return this.achievementCategories;
	}

	public void setAchievementCategories(List<Integer> val) {
		this.achievementCategories = val;
	}

	public List<String> getAchievementGroups() {
		return this.achievementGroups;
	}

	public void setAchievementGroups(List<String> val) {
		this.achievementGroups = val;
	}

	public List<String> getCharacters() {
		return this.characters;
	}

	public void setCharacters(List<String> val) {
		this.characters = val;
	}

	public List<Integer> getCommerceListings() {
		return this.commerceListings;
	}

	public void setCommerceListings(List<Integer> val) {
		this.commerceListings = val;
	}

	public List<Integer> getCommercePrices() {
		return this.commercePrices;
	}

	public void setCommercePrices(List<Integer> val) {
		this.commercePrices = val;
	}

	public List<Object> getCommerceCurrentBuyTransactions() {
		return this.commerceCurrentBuyTransactions;
	}

	public void setCommerceCurrentBuyTransactions(List<Object> val) {
		this.commerceCurrentBuyTransactions = val;
	}

	public List<CommerceCurrentSellTransactions> getCommerceCurrentSellTransactions() {
		return this.commerceCurrentSellTransactions;
	}

	public void setCommerceCurrentSellTransactions(List<CommerceCurrentSellTransactions> val) {
		this.commerceCurrentSellTransactions = val;
	}

	public List<Object> getCommercePastBuyTransactions() {
		return this.commercePastBuyTransactions;
	}

	public void setCommercePastBuyTransactions(List<Object> val) {
		this.commercePastBuyTransactions = val;
	}

	public List<Object> getCommercePastSellTransactions() {
		return this.commercePastSellTransactions;
	}

	public void setCommercePastSellTransactions(List<Object> val) {
		this.commercePastSellTransactions = val;
	}

	public List<String> getPvpGames() {
		return this.pvpGames;
	}

	public void setPvpGames(List<String> val) {
		this.pvpGames = val;
	}

	public List<Integer> getPvpAmulets() {
		return this.pvpAmulets;
	}

	public void setPvpAmulets(List<Integer> val) {
		this.pvpAmulets = val;
	}

	public List<String> getPvpSeasons() {
		return this.pvpSeasons;
	}

	public void setPvpSeasons(List<String> val) {
		this.pvpSeasons = val;
	}

	public List<PvpStandings> getPvpStandings() {
		return this.pvpStandings;
	}

	public void setPvpStandings(List<PvpStandings> val) {
		this.pvpStandings = val;
	}

	public List<String> getWvwMatches() {
		return this.wvwMatches;
	}

	public void setWvwMatches(List<String> val) {
		this.wvwMatches = val;
	}

	public List<String> getWvwObjectives() {
		return this.wvwObjectives;
	}

	public void setWvwObjectives(List<String> val) {
		this.wvwObjectives = val;
	}

	public List<Integer> getColors() {
		return this.colors;
	}

	public void setColors(List<Integer> val) {
		this.colors = val;
	}

	public List<Integer> getContinents() {
		return this.continents;
	}

	public void setContinents(List<Integer> val) {
		this.continents = val;
	}

	public List<Integer> getCurrencies() {
		return this.currencies;
	}

	public void setCurrencies(List<Integer> val) {
		this.currencies = val;
	}

	public List<Integer> getEmblemForegrounds() {
		return this.emblemForegrounds;
	}

	public void setEmblemForegrounds(List<Integer> val) {
		this.emblemForegrounds = val;
	}

	public List<Integer> getEmblemBackgrounds() {
		return this.emblemBackgrounds;
	}

	public void setEmblemBackgrounds(List<Integer> val) {
		this.emblemBackgrounds = val;
	}

	public List<String> getFiles() {
		return this.files;
	}

	public void setFiles(List<String> val) {
		this.files = val;
	}

	public List<Integer> getItems() {
		return this.items;
	}

	public void setItems(List<Integer> val) {
		this.items = val;
	}

	public List<Integer> getAllItemStats() {
		return this.allItemStats;
	}

	public void setAllItemStats(List<Integer> val) {
		this.allItemStats = val;
	}

	public List<String> getLegends() {
		return this.legends;
	}

	public void setLegends(List<String> val) {
		this.legends = val;
	}

	public List<Integer> getMaps() {
		return this.maps;
	}

	public void setMaps(List<Integer> val) {
		this.maps = val;
	}

	public List<Integer> getAllMaterials() {
		return this.allMaterials;
	}

	public void setAllMaterials(List<Integer> val) {
		this.allMaterials = val;
	}

	public List<Integer> getMinis() {
		return this.minis;
	}

	public void setMinis(List<Integer> val) {
		this.minis = val;
	}

	public List<Integer> getPets() {
		return this.pets;
	}

	public void setPets(List<Integer> val) {
		this.pets = val;
	}

	public List<String> getProfessions() {
		return this.professions;
	}

	public void setProfessions(List<String> val) {
		this.professions = val;
	}

	public List<String> getQuaggans() {
		return this.quaggans;
	}

	public void setQuaggans(List<String> val) {
		this.quaggans = val;
	}

	public List<Integer> getRecipes() {
		return this.recipes;
	}

	public void setRecipes(List<Integer> val) {
		this.recipes = val;
	}

	public List<Integer> getSkills() {
		return this.skills;
	}

	public void setSkills(List<Integer> val) {
		this.skills = val;
	}

	public List<Integer> getSkins() {
		return this.skins;
	}

	public void setSkins(List<Integer> val) {
		this.skins = val;
	}

	public List<Integer> getSpecializations() {
		return this.specializations;
	}

	public void setSpecializations(List<Integer> val) {
		this.specializations = val;
	}

	public List<Integer> getTitles() {
		return this.titles;
	}

	public void setTitles(List<Integer> val) {
		this.titles = val;
	}

	public List<Integer> getTraits() {
		return this.traits;
	}

	public void setTraits(List<Integer> val) {
		this.traits = val;
	}

	public List<Integer> getWorlds() {
		return this.worlds;
	}

	public void setWorlds(List<Integer> val) {
		this.worlds = val;
	}

	public GeneratedJsonArrays() {
		this.accountAchievements = new ArrayList<AccountAchievements>();
		this.accountBank = new ArrayList<AccountBank>();
		this.accountDyes = new ArrayList<Integer>();
		this.accountInventory = new ArrayList<String>();
		this.accountMaterials = new ArrayList<AccountMaterials>();
		this.accountMinis = new ArrayList<Integer>();
		this.accountSkins = new ArrayList<Integer>();
		this.accountTitles = new ArrayList<Integer>();
		this.accountWallet = new ArrayList<AccountWallet>();
		this.achievements = new ArrayList<Integer>();
		this.achievementCategories = new ArrayList<Integer>();
		this.achievementGroups = new ArrayList<String>();
		this.characters = new ArrayList<String>();
		this.commerceListings = new ArrayList<Integer>();
		this.commercePrices = new ArrayList<Integer>();
		this.commerceCurrentBuyTransactions = new ArrayList<Object>();
		this.commerceCurrentSellTransactions = new ArrayList<CommerceCurrentSellTransactions>();
		this.commercePastBuyTransactions = new ArrayList<Object>();
		this.commercePastSellTransactions = new ArrayList<Object>();
		this.pvpGames = new ArrayList<String>();
		this.pvpAmulets = new ArrayList<Integer>();
		this.pvpSeasons = new ArrayList<String>();
		this.pvpStandings = new ArrayList<PvpStandings>();
		this.wvwMatches = new ArrayList<String>();
		this.wvwObjectives = new ArrayList<String>();
		this.colors = new ArrayList<Integer>();
		this.continents = new ArrayList<Integer>();
		this.currencies = new ArrayList<Integer>();
		this.emblemForegrounds = new ArrayList<Integer>();
		this.emblemBackgrounds = new ArrayList<Integer>();
		this.files = new ArrayList<String>();
		this.items = new ArrayList<Integer>();
		this.allItemStats = new ArrayList<Integer>();
		this.legends = new ArrayList<String>();
		this.maps = new ArrayList<Integer>();
		this.allMaterials = new ArrayList<Integer>();
		this.minis = new ArrayList<Integer>();
		this.pets = new ArrayList<Integer>();
		this.professions = new ArrayList<String>();
		this.quaggans = new ArrayList<String>();
		this.recipes = new ArrayList<Integer>();
		this.skills = new ArrayList<Integer>();
		this.skins = new ArrayList<Integer>();
		this.specializations = new ArrayList<Integer>();
		this.titles = new ArrayList<Integer>();
		this.traits = new ArrayList<Integer>();
		this.worlds = new ArrayList<Integer>();
	}

}
