package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ItemStatsAttributes extends JsonModelFactoryMaster {

	private Double Toughness;

	private Double Vitality;

	//Getters and setters

	public Double getToughness() {
		return this.Toughness;
	}

	public void setToughness(Double val) {
		this.Toughness = val;
	}

	public Double getVitality() {
		return this.Vitality;
	}

	public void setVitality(Double val) {
		this.Vitality = val;
	}

	public ItemStatsAttributes() {
	}

}
