package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ItemDetails extends JsonModelFactoryMaster {

	private ItemDetailsInfixUpgrade infixUpgrade;

	private String weightClass;

	private String secondarySuffixItemId;

	private Integer defense;

	private Integer suffixItemId;

	private List<Object> infusionSlots; //TODO: GW-0001 

	private String type;

	//Getters and setters

	public ItemDetailsInfixUpgrade getInfixUpgrade() {
		return this.infixUpgrade;
	}

	public void setInfixUpgrade(ItemDetailsInfixUpgrade val) {
		this.infixUpgrade = val;
	}

	public String getWeightClass() {
		return this.weightClass;
	}

	public void setWeightClass(String val) {
		this.weightClass = val;
	}

	public String getSecondarySuffixItemId() {
		return this.secondarySuffixItemId;
	}

	public void setSecondarySuffixItemId(String val) {
		this.secondarySuffixItemId = val;
	}

	public Integer getDefense() {
		return this.defense;
	}

	public void setDefense(Integer val) {
		this.defense = val;
	}

	public Integer getSuffixItemId() {
		return this.suffixItemId;
	}

	public void setSuffixItemId(Integer val) {
		this.suffixItemId = val;
	}

	public List<Object> getInfusionSlots() {
		return this.infusionSlots;
	}

	public void setInfusionSlots(List<Object> val) {
		this.infusionSlots = val;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String val) {
		this.type = val;
	}

	public ItemDetails() {
		this.infusionSlots = new ArrayList<Object>();
	}

}
