package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsScepter extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsScepterSkills> skills;

	//Getters and setters

	public List<ProfessionWeaponsScepterSkills> getSkills() {
		return this.skills;
	}

	public void setSkills(List<ProfessionWeaponsScepterSkills> val) {
		this.skills = val;
	}

	public ProfessionWeaponsScepter() {
		this.skills = new ArrayList<ProfessionWeaponsScepterSkills>();
	}

}
