package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsTrident extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsTridentSkills> skills;

	//Getters and setters

	public List<ProfessionWeaponsTridentSkills> getSkills() {
		return this.skills;
	}

	public void setSkills(List<ProfessionWeaponsTridentSkills> val) {
		this.skills = val;
	}

	public ProfessionWeaponsTrident() {
		this.skills = new ArrayList<ProfessionWeaponsTridentSkills>();
	}

}
