package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionTrainingTrack extends JsonModelFactoryMaster {

	private Integer cost;

	private Integer skillId;

	private String type;

	//Getters and setters

	public Integer getCost() {
		return this.cost;
	}

	public void setCost(Integer val) {
		this.cost = val;
	}

	public Integer getSkillId() {
		return this.skillId;
	}

	public void setSkillId(Integer val) {
		this.skillId = val;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String val) {
		this.type = val;
	}

	public ProfessionTrainingTrack() {
	}

}
