package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsSpear extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsSpearSkills> skills;

	//Getters and setters

	public List<ProfessionWeaponsSpearSkills> getSkills() {
		return this.skills;
	}

	public void setSkills(List<ProfessionWeaponsSpearSkills> val) {
		this.skills = val;
	}

	public ProfessionWeaponsSpear() {
		this.skills = new ArrayList<ProfessionWeaponsSpearSkills>();
	}

}
