package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsTridentSkills extends JsonModelFactoryMaster {

	private Integer id;

	private String slot;

	//Getters and setters

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public String getSlot() {
		return this.slot;
	}

	public void setSlot(String val) {
		this.slot = val;
	}

	public ProfessionWeaponsTridentSkills() {
	}

}
