package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsMace extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsMaceSkills> skills;

	//Getters and setters

	public List<ProfessionWeaponsMaceSkills> getSkills() {
		return this.skills;
	}

	public void setSkills(List<ProfessionWeaponsMaceSkills> val) {
		this.skills = val;
	}

	public ProfessionWeaponsMace() {
		this.skills = new ArrayList<ProfessionWeaponsMaceSkills>();
	}

}
