package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsShield extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsShieldSkills> skills;

	//Getters and setters

	public List<ProfessionWeaponsShieldSkills> getSkills() {
		return this.skills;
	}

	public void setSkills(List<ProfessionWeaponsShieldSkills> val) {
		this.skills = val;
	}

	public ProfessionWeaponsShield() {
		this.skills = new ArrayList<ProfessionWeaponsShieldSkills>();
	}

}
