package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpAmuletAttributes extends JsonModelFactoryMaster {

	private Integer Toughness;

	private Integer Precision;

	private Integer Power;

	//Getters and setters

	public Integer getToughness() {
		return this.Toughness;
	}

	public void setToughness(Integer val) {
		this.Toughness = val;
	}

	public Integer getPrecision() {
		return this.Precision;
	}

	public void setPrecision(Integer val) {
		this.Precision = val;
	}

	public Integer getPower() {
		return this.Power;
	}

	public void setPower(Integer val) {
		this.Power = val;
	}

	public PvpAmuletAttributes() {
	}

}
