package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/pvp/games/10801E29-4CF1-4F7E-82B6-FC1F8A90855D?access_token=79D451B9-26E6-6943-BDA6-AC9D05EE563DA640C336-0F50-4875-8350-23E6C642A0F1
 */
public class PvpGame extends JsonModelFactoryMaster {

	private String result;

	private String profession;

	private Integer mapId;

	private PvpGameScores scores;

	private String ratingType;

	private String ended;

	private String season;

	private String started;

	private String id;

	private String team;

	//Getters and setters

	public String getResult() {
		return this.result;
	}

	public void setResult(String val) {
		this.result = val;
	}

	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String val) {
		this.profession = val;
	}

	public Integer getMapId() {
		return this.mapId;
	}

	public void setMapId(Integer val) {
		this.mapId = val;
	}

	public PvpGameScores getScores() {
		return this.scores;
	}

	public void setScores(PvpGameScores val) {
		this.scores = val;
	}

	public String getRatingType() {
		return this.ratingType;
	}

	public void setRatingType(String val) {
		this.ratingType = val;
	}

	public String getEnded() {
		return this.ended;
	}

	public void setEnded(String val) {
		this.ended = val;
	}

	public String getSeason() {
		return this.season;
	}

	public void setSeason(String val) {
		this.season = val;
	}

	public String getStarted() {
		return this.started;
	}

	public void setStarted(String val) {
		this.started = val;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String val) {
		this.id = val;
	}

	public String getTeam() {
		return this.team;
	}

	public void setTeam(String val) {
		this.team = val;
	}

	public PvpGame() {
	}

}
