package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpGameScores extends JsonModelFactoryMaster {

	private Integer red;

	private Integer blue;

	//Getters and setters

	public Integer getRed() {
		return this.red;
	}

	public void setRed(Integer val) {
		this.red = val;
	}

	public Integer getBlue() {
		return this.blue;
	}

	public void setBlue(Integer val) {
		this.blue = val;
	}

	public PvpGameScores() {
	}

}
