package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpStatsProfessions extends JsonModelFactoryMaster {

	private PvpStatsProfessionsRevenant revenant;

	private PvpStatsProfessionsThief thief;

	private PvpStatsProfessionsWarrior warrior;

	private PvpStatsProfessionsNecromancer necromancer;

	private PvpStatsProfessionsRanger ranger;

	private PvpStatsProfessionsMesmer mesmer;

	private PvpStatsProfessionsGuardian guardian;

	private PvpStatsProfessionsElementalist elementalist;

	private PvpStatsProfessionsEngineer engineer;

	//Getters and setters

	public PvpStatsProfessionsRevenant getRevenant() {
		return this.revenant;
	}

	public void setRevenant(PvpStatsProfessionsRevenant val) {
		this.revenant = val;
	}

	public PvpStatsProfessionsThief getThief() {
		return this.thief;
	}

	public void setThief(PvpStatsProfessionsThief val) {
		this.thief = val;
	}

	public PvpStatsProfessionsWarrior getWarrior() {
		return this.warrior;
	}

	public void setWarrior(PvpStatsProfessionsWarrior val) {
		this.warrior = val;
	}

	public PvpStatsProfessionsNecromancer getNecromancer() {
		return this.necromancer;
	}

	public void setNecromancer(PvpStatsProfessionsNecromancer val) {
		this.necromancer = val;
	}

	public PvpStatsProfessionsRanger getRanger() {
		return this.ranger;
	}

	public void setRanger(PvpStatsProfessionsRanger val) {
		this.ranger = val;
	}

	public PvpStatsProfessionsMesmer getMesmer() {
		return this.mesmer;
	}

	public void setMesmer(PvpStatsProfessionsMesmer val) {
		this.mesmer = val;
	}

	public PvpStatsProfessionsGuardian getGuardian() {
		return this.guardian;
	}

	public void setGuardian(PvpStatsProfessionsGuardian val) {
		this.guardian = val;
	}

	public PvpStatsProfessionsElementalist getElementalist() {
		return this.elementalist;
	}

	public void setElementalist(PvpStatsProfessionsElementalist val) {
		this.elementalist = val;
	}

	public PvpStatsProfessionsEngineer getEngineer() {
		return this.engineer;
	}

	public void setEngineer(PvpStatsProfessionsEngineer val) {
		this.engineer = val;
	}

	public PvpStatsProfessions() {
	}

}
