package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpSeasonDivisions extends JsonModelFactoryMaster {

	private List<PvpSeasonDivisionsTiers> tiers;

	private String name;

	private List<Object> flags; //TODO: GW-0001 

	private String largeIcon;

	private String smallIcon;

	private String pipIcon;

	//Getters and setters

	public List<PvpSeasonDivisionsTiers> getTiers() {
		return this.tiers;
	}

	public void setTiers(List<PvpSeasonDivisionsTiers> val) {
		this.tiers = val;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String val) {
		this.name = val;
	}

	public List<Object> getFlags() {
		return this.flags;
	}

	public void setFlags(List<Object> val) {
		this.flags = val;
	}

	public String getLargeIcon() {
		return this.largeIcon;
	}

	public void setLargeIcon(String val) {
		this.largeIcon = val;
	}

	public String getSmallIcon() {
		return this.smallIcon;
	}

	public void setSmallIcon(String val) {
		this.smallIcon = val;
	}

	public String getPipIcon() {
		return this.pipIcon;
	}

	public void setPipIcon(String val) {
		this.pipIcon = val;
	}

	public PvpSeasonDivisions() {
		this.tiers = new ArrayList<PvpSeasonDivisionsTiers>();
		this.flags = new ArrayList<Object>();
	}

}
