package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/pvp/stats?access_token=79D451B9-26E6-6943-BDA6-AC9D05EE563DA640C336-0F50-4875-8350-23E6C642A0F1
 */
public class PvpStats extends JsonModelFactoryMaster {

	private Integer pvpRank;

	private Integer pvpRankPoints;

	private PvpStatsLadders ladders;

	private PvpStatsProfessions professions;

	private Integer pvpRankRollovers;

	private PvpStatsAggregate aggregate;

	//Getters and setters

	public Integer getPvpRank() {
		return this.pvpRank;
	}

	public void setPvpRank(Integer val) {
		this.pvpRank = val;
	}

	public Integer getPvpRankPoints() {
		return this.pvpRankPoints;
	}

	public void setPvpRankPoints(Integer val) {
		this.pvpRankPoints = val;
	}

	public PvpStatsLadders getLadders() {
		return this.ladders;
	}

	public void setLadders(PvpStatsLadders val) {
		this.ladders = val;
	}

	public PvpStatsProfessions getProfessions() {
		return this.professions;
	}

	public void setProfessions(PvpStatsProfessions val) {
		this.professions = val;
	}

	public Integer getPvpRankRollovers() {
		return this.pvpRankRollovers;
	}

	public void setPvpRankRollovers(Integer val) {
		this.pvpRankRollovers = val;
	}

	public PvpStatsAggregate getAggregate() {
		return this.aggregate;
	}

	public void setAggregate(PvpStatsAggregate val) {
		this.aggregate = val;
	}

	public PvpStats() {
	}

}
