package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class RecipeIngredients extends JsonModelFactoryMaster {

	private Integer itemId;

	private Integer count;

	//Getters and setters

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer val) {
		this.itemId = val;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer val) {
		this.count = val;
	}

	public RecipeIngredients() {
	}

}
