package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class SkillFacts extends JsonModelFactoryMaster {

	private String icon;

	private String text;

	private String type;

	private Integer hitCount;

	private Integer value;

	//Getters and setters

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String val) {
		this.icon = val;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String val) {
		this.text = val;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String val) {
		this.type = val;
	}

	public Integer getHitCount() {
		return this.hitCount;
	}

	public void setHitCount(Integer val) {
		this.hitCount = val;
	}

	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer val) {
		this.value = val;
	}

	public SkillFacts() {
	}

}
