package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class SkinDetails extends JsonModelFactoryMaster {

	private String weightClass;

	private String type;

	//Getters and setters

	public String getWeightClass() {
		return this.weightClass;
	}

	public void setWeightClass(String val) {
		this.weightClass = val;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String val) {
		this.type = val;
	}

	public SkinDetails() {
	}

}
