package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/titles/43
 */
public class Title extends JsonModelFactoryMaster {

	private Integer achievement;

	private String name;

	private Integer id;

	//Getters and setters

	public Integer getAchievement() {
		return this.achievement;
	}

	public void setAchievement(Integer val) {
		this.achievement = val;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String val) {
		this.name = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public Title() {
	}

}
