package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/tokeninfo?access_token=79D451B9-26E6-6943-BDA6-AC9D05EE563DA640C336-0F50-4875-8350-23E6C642A0F1
 */
public class TokenInfo extends JsonModelFactoryMaster {

	private List<String> permissions;

	private String name;

	private String id;

	//Getters and setters

	public List<String> getPermissions() {
		return this.permissions;
	}

	public void setPermissions(List<String> val) {
		this.permissions = val;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String val) {
		this.name = val;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String val) {
		this.id = val;
	}

	public TokenInfo() {
		this.permissions = new ArrayList<String>();
	}

}
