package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/traits/214
 */
public class Trait extends JsonModelFactoryMaster {

	private Integer tier;

	private List<TraitTraitedFacts> traitedFacts;

	private String name;

	private String icon;

	private String description;

	private Integer specialization;

	private Integer id;

	private String slot;

	private List<TraitFacts> facts;

	private Integer order;

	//Getters and setters

	public Integer getTier() {
		return this.tier;
	}

	public void setTier(Integer val) {
		this.tier = val;
	}

	public List<TraitTraitedFacts> getTraitedFacts() {
		return this.traitedFacts;
	}

	public void setTraitedFacts(List<TraitTraitedFacts> val) {
		this.traitedFacts = val;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String val) {
		this.name = val;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String val) {
		this.icon = val;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String val) {
		this.description = val;
	}

	public Integer getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(Integer val) {
		this.specialization = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public String getSlot() {
		return this.slot;
	}

	public void setSlot(String val) {
		this.slot = val;
	}

	public List<TraitFacts> getFacts() {
		return this.facts;
	}

	public void setFacts(List<TraitFacts> val) {
		this.facts = val;
	}

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer val) {
		this.order = val;
	}

	public Trait() {
		this.traitedFacts = new ArrayList<TraitTraitedFacts>();
		this.facts = new ArrayList<TraitFacts>();
	}

}
