package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class AccountAchievements extends JsonModelFactoryMaster {

	private Integer current;

	private Integer max;

	private List<String> bits;

	private Integer id;

	private Boolean done;

	private Integer repeated;

	private Boolean unlocked;

	//Getters and setters

	public Integer getCurrent() {
		return this.current;
	}

	public void setCurrent(Integer val) {
		this.current = val;
	}

	public Integer getMax() {
		return this.max;
	}

	public void setMax(Integer val) {
		this.max = val;
	}

	public List<String> getBits() {
		return this.bits;
	}

	public void setBits(List<String> val) {
		this.bits = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public Boolean getDone() {
		return this.done;
	}

	public void setDone(Boolean val) {
		this.done = val;
	}

	public Integer getRepeated() {
		return this.repeated;
	}

	public void setRepeated(Integer val) {
		this.repeated = val;
	}

	public Boolean getUnlocked() {
		return this.unlocked;
	}

	public void setUnlocked(Boolean val) {
		this.unlocked = val;
	}

	public AccountAchievements() {
		this.bits = new ArrayList<String>();
	}

}
