package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class AccountWallet extends JsonModelFactoryMaster {

	private Integer id;

	private Integer value;

	//Getters and setters

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer val) {
		this.value = val;
	}

	public AccountWallet() {
	}

}
