package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/achievements/categories/29
 */
public class AchievementCategory extends JsonModelFactoryMaster {

	private String name;

	private String icon;

	private String description;

	private Integer id;

	private Integer order;

}
