package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/achievements/groups/65B4B678-607E-4D97-B458-076C3E96A810
 */
public class AchievementGroup extends JsonModelFactoryMaster {

	private String name;

	private String description;

	private String id;

	private List<Integer> categories;

	private Integer order;

}
