package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CharacterCraftingCrafting extends JsonModelFactoryMaster {

	private Integer rating;

	private Boolean active;

	private String discipline;

	//Getters and setters

	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer val) {
		this.rating = val;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean val) {
		this.active = val;
	}

	public String getDiscipline() {
		return this.discipline;
	}

	public void setDiscipline(String val) {
		this.discipline = val;
	}

	public CharacterCraftingCrafting() {
	}

}
