package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CharacterEquipmentEquipment extends JsonModelFactoryMaster {

	private List<Integer> infusions;

	private CharacterEquipmentEquipmentStats characterEquipmentEquipmentStats;

	private Integer skin;

	private Integer id;

	private String slot;

	private List<Integer> upgrades;

}
