package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CharacterEquipmentEquipmentStats extends JsonModelFactoryMaster {

	private CharacterEquipmentEquipmentStatsAttributes characterEquipmentEquipmentStatsAttributes;

	private Integer id;

	//Getters and setters

	public CharacterEquipmentEquipmentStatsAttributes getCharacterEquipmentEquipmentStatsAttributes() {
		return this.characterEquipmentEquipmentStatsAttributes;
	}

	public void setCharacterEquipmentEquipmentStatsAttributes(CharacterEquipmentEquipmentStatsAttributes val) {
		this.characterEquipmentEquipmentStatsAttributes = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public CharacterEquipmentEquipmentStats() {
	}

}
