package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CharacterCraftingCrafting extends JsonModelFactoryMaster {

	private Integer rating;

	private Boolean active;

	private String discipline;

}
