package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CharacterSpecializationsSpecializationsPvp extends JsonModelFactoryMaster {

	private List<Integer> traits;

	private Integer id;

	//Getters and setters

	public List<Integer> getTraits() {
		return this.traits;
	}

	public void setTraits(List<Integer> val) {
		this.traits = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public CharacterSpecializationsSpecializationsPvp() {
		this.traits = new ArrayList<Integer>();
	}

}
