package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CharacterSpecializationsSpecializations extends JsonModelFactoryMaster {

	private List<CharacterSpecializationsSpecializationsWvw> wvw;

	private List<CharacterSpecializationsSpecializationsPvp> pvp;

	private List<CharacterSpecializationsSpecializationsPve> pve;

	//Getters and setters

	public List<CharacterSpecializationsSpecializationsWvw> getWvw() {
		return this.wvw;
	}

	public void setWvw(List<CharacterSpecializationsSpecializationsWvw> val) {
		this.wvw = val;
	}

	public List<CharacterSpecializationsSpecializationsPvp> getPvp() {
		return this.pvp;
	}

	public void setPvp(List<CharacterSpecializationsSpecializationsPvp> val) {
		this.pvp = val;
	}

	public List<CharacterSpecializationsSpecializationsPve> getPve() {
		return this.pve;
	}

	public void setPve(List<CharacterSpecializationsSpecializationsPve> val) {
		this.pve = val;
	}

	public CharacterSpecializationsSpecializations() {
		this.wvw = new ArrayList<CharacterSpecializationsSpecializationsWvw>();
		this.pvp = new ArrayList<CharacterSpecializationsSpecializationsPvp>();
		this.pve = new ArrayList<CharacterSpecializationsSpecializationsPve>();
	}

}
