package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CharacterSpecializationsSpecializations extends JsonModelFactoryMaster {

	private List<CharacterSpecializationsSpecializationsWvw> characterSpecializationsSpecializationsWvw;

	private List<CharacterSpecializationsSpecializationsPvp> characterSpecializationsSpecializationsPvp;

	private List<CharacterSpecializationsSpecializationsPve> characterSpecializationsSpecializationsPve;

	//Getters and setters

	public List<CharacterSpecializationsSpecializationsWvw> getCharacterSpecializationsSpecializationsWvw() {
		return this.characterSpecializationsSpecializationsWvw;
	}

	public void setCharacterSpecializationsSpecializationsWvw(List<CharacterSpecializationsSpecializationsWvw> val) {
		this.characterSpecializationsSpecializationsWvw = val;
	}

	public List<CharacterSpecializationsSpecializationsPvp> getCharacterSpecializationsSpecializationsPvp() {
		return this.characterSpecializationsSpecializationsPvp;
	}

	public void setCharacterSpecializationsSpecializationsPvp(List<CharacterSpecializationsSpecializationsPvp> val) {
		this.characterSpecializationsSpecializationsPvp = val;
	}

	public List<CharacterSpecializationsSpecializationsPve> getCharacterSpecializationsSpecializationsPve() {
		return this.characterSpecializationsSpecializationsPve;
	}

	public void setCharacterSpecializationsSpecializationsPve(List<CharacterSpecializationsSpecializationsPve> val) {
		this.characterSpecializationsSpecializationsPve = val;
	}

	public CharacterSpecializationsSpecializations() {
		this.characterSpecializationsSpecializationsWvw = new ArrayList<CharacterSpecializationsSpecializationsWvw>();
		this.characterSpecializationsSpecializationsPvp = new ArrayList<CharacterSpecializationsSpecializationsPvp>();
		this.characterSpecializationsSpecializationsPve = new ArrayList<CharacterSpecializationsSpecializationsPve>();
	}

}
