package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CharacterInventoryBags extends JsonModelFactoryMaster {

	private Integer size;

	private Integer id;

	private List<CharacterInventoryBagsInventory> inventory;

	//Getters and setters

	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer val) {
		this.size = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public List<CharacterInventoryBagsInventory> getInventory() {
		return this.inventory;
	}

	public void setInventory(List<CharacterInventoryBagsInventory> val) {
		this.inventory = val;
	}

	public CharacterInventoryBags() {
		this.inventory = new ArrayList<CharacterInventoryBagsInventory>();
	}

}
