package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CharacterEquipmentEquipmentStats extends JsonModelFactoryMaster {

	private CharacterEquipmentEquipmentStatsAttributes characterEquipmentEquipmentStatsAttributes;

	private Integer id;

}
