package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CharacterInventoryBagsInventory extends JsonModelFactoryMaster {

	private Integer count;

	private String binding;

	private Integer id;

}
