package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/colors/6
 */
public class Color extends JsonModelFactoryMaster {

	private Integer item;

	private List<Integer> baseRgb;

	private String name;

	private ColorMetal metal;

	private Integer id;

	private List<String> categories;

	private ColorLeather leather;

	private ColorCloth cloth;

	//Getters and setters

	public Integer getItem() {
		return this.item;
	}

	public void setItem(Integer val) {
		this.item = val;
	}

	public List<Integer> getBaseRgb() {
		return this.baseRgb;
	}

	public void setBaseRgb(List<Integer> val) {
		this.baseRgb = val;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String val) {
		this.name = val;
	}

	public ColorMetal getMetal() {
		return this.metal;
	}

	public void setMetal(ColorMetal val) {
		this.metal = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public List<String> getCategories() {
		return this.categories;
	}

	public void setCategories(List<String> val) {
		this.categories = val;
	}

	public ColorLeather getLeather() {
		return this.leather;
	}

	public void setLeather(ColorLeather val) {
		this.leather = val;
	}

	public ColorCloth getCloth() {
		return this.cloth;
	}

	public void setCloth(ColorCloth val) {
		this.cloth = val;
	}

	public Color() {
		this.baseRgb = new ArrayList<Integer>();
		this.categories = new ArrayList<String>();
	}

}
