package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ColorCloth extends JsonModelFactoryMaster {

	private Double saturation;

	private Integer brightness;

	private Double contrast;

	private Double lightness;

	private Integer hue;

}
