package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/colors/6
 */
public class Color extends JsonModelFactoryMaster {

	private Integer item;

	private List<Integer> baseRgb;

	private String name;

	private ColorMetal colorMetal;

	private Integer id;

	private List<String> categories;

	private ColorLeather colorLeather;

	private ColorCloth colorCloth;

}
