package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/commerce/listings/1178
 */
public class CommerceListing extends JsonModelFactoryMaster {

	private List<CommerceListingBuys> commerceListingBuys;

	private List<CommerceListingSells> commerceListingSells;

	private Integer id;

	//Getters and setters

	public List<CommerceListingBuys> getCommerceListingBuys() {
		return this.commerceListingBuys;
	}

	public void setCommerceListingBuys(List<CommerceListingBuys> val) {
		this.commerceListingBuys = val;
	}

	public List<CommerceListingSells> getCommerceListingSells() {
		return this.commerceListingSells;
	}

	public void setCommerceListingSells(List<CommerceListingSells> val) {
		this.commerceListingSells = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public CommerceListing() {
		this.commerceListingBuys = new ArrayList<CommerceListingBuys>();
		this.commerceListingSells = new ArrayList<CommerceListingSells>();
	}

}
