package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class CommercePriceBuys extends JsonModelFactoryMaster {

	private Integer quantity;

	private Integer unitPrice;

	//Getters and setters

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer val) {
		this.quantity = val;
	}

	public Integer getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Integer val) {
		this.unitPrice = val;
	}

	public CommercePriceBuys() {
	}

}
