package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/commerce/exchange/coins?quantity=10000
 */
public class CommerceExchangeCoins extends JsonModelFactoryMaster {

	private Integer coinsPerGem;

	private Integer quantity;

}
