package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/commerce/listings/1178
 */
public class CommerceListing extends JsonModelFactoryMaster {

	private List<CommerceListingBuys> commerceListingBuys;

	private List<CommerceListingSells> commerceListingSells;

	private Integer id;

}
