package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/commerce/prices/1178
 */
public class CommercePrice extends JsonModelFactoryMaster {

	private CommercePriceBuys commercePriceBuys;

	private CommercePriceSells commercePriceSells;

	private Integer id;

	private Boolean whitelisted;

}
