package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class DailyAchievementsPveLevel extends JsonModelFactoryMaster {

	private Integer min;

	private Integer max;

}
