package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/achievements/daily
 */
public class DailyAchievements extends JsonModelFactoryMaster {

	private List<Object> special; //TODO: GW-0001 

	private List<DailyAchievementsWvw> dailyAchievementsWvw;

	private List<DailyAchievementsPvp> dailyAchievementsPvp;

	private List<DailyAchievementsPve> dailyAchievementsPve;

}
