package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class DailyAchievementsPvp extends JsonModelFactoryMaster {

	private DailyAchievementsPvpLevel dailyAchievementsPvpLevel;

	private Integer id;

	private List<String> requiredAccess;

}
