package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/achievements/daily
 */
public class DailyAchievements extends JsonModelFactoryMaster {

	private List<Object> special; //TODO: GW-0001 

	private List<DailyAchievementsWvw> dailyAchievementsWvw;

	private List<DailyAchievementsPvp> dailyAchievementsPvp;

	private List<DailyAchievementsPve> dailyAchievementsPve;

	//Getters and setters

	public List<Object> getSpecial() {
		return this.special;
	}

	public void setSpecial(List<Object> val) {
		this.special = val;
	}

	public List<DailyAchievementsWvw> getDailyAchievementsWvw() {
		return this.dailyAchievementsWvw;
	}

	public void setDailyAchievementsWvw(List<DailyAchievementsWvw> val) {
		this.dailyAchievementsWvw = val;
	}

	public List<DailyAchievementsPvp> getDailyAchievementsPvp() {
		return this.dailyAchievementsPvp;
	}

	public void setDailyAchievementsPvp(List<DailyAchievementsPvp> val) {
		this.dailyAchievementsPvp = val;
	}

	public List<DailyAchievementsPve> getDailyAchievementsPve() {
		return this.dailyAchievementsPve;
	}

	public void setDailyAchievementsPve(List<DailyAchievementsPve> val) {
		this.dailyAchievementsPve = val;
	}

	public DailyAchievements() {
		this.special = new ArrayList<Object>();
		this.dailyAchievementsWvw = new ArrayList<DailyAchievementsWvw>();
		this.dailyAchievementsPvp = new ArrayList<DailyAchievementsPvp>();
		this.dailyAchievementsPve = new ArrayList<DailyAchievementsPve>();
	}

}
