package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class DailyAchievementsPvp extends JsonModelFactoryMaster {

	private DailyAchievementsPvpLevel level;

	private Integer id;

	private List<String> requiredAccess;

	//Getters and setters

	public DailyAchievementsPvpLevel getLevel() {
		return this.level;
	}

	public void setLevel(DailyAchievementsPvpLevel val) {
		this.level = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public List<String> getRequiredAccess() {
		return this.requiredAccess;
	}

	public void setRequiredAccess(List<String> val) {
		this.requiredAccess = val;
	}

	public DailyAchievementsPvp() {
		this.requiredAccess = new ArrayList<String>();
	}

}
