package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/achievements/daily
 */
public class DailyAchievements extends JsonModelFactoryMaster {

	private List<Object> special; //TODO: GW-0001 

	private List<DailyAchievementsWvw> wvw;

	private List<DailyAchievementsPvp> pvp;

	private List<DailyAchievementsPve> pve;

	//Getters and setters

	public List<Object> getSpecial() {
		return this.special;
	}

	public void setSpecial(List<Object> val) {
		this.special = val;
	}

	public List<DailyAchievementsWvw> getWvw() {
		return this.wvw;
	}

	public void setWvw(List<DailyAchievementsWvw> val) {
		this.wvw = val;
	}

	public List<DailyAchievementsPvp> getPvp() {
		return this.pvp;
	}

	public void setPvp(List<DailyAchievementsPvp> val) {
		this.pvp = val;
	}

	public List<DailyAchievementsPve> getPve() {
		return this.pve;
	}

	public void setPve(List<DailyAchievementsPve> val) {
		this.pve = val;
	}

	public DailyAchievements() {
		this.special = new ArrayList<Object>();
		this.wvw = new ArrayList<DailyAchievementsWvw>();
		this.pvp = new ArrayList<DailyAchievementsPvp>();
		this.pve = new ArrayList<DailyAchievementsPve>();
	}

}
