package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/emblem/foregrounds/1
 */
public class EmblemForeground extends JsonModelFactoryMaster {

	private List<String> layers;

	private Integer id;

}
