package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/files/wvw_battles_hollow_red
 */
public class File extends JsonModelFactoryMaster {

	private String icon;

	private String id;

}
