package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Array class containing all arrays from the config file.
 */
public class GeneratedJsonArrays extends JsonModelFactoryMaster {

	private List<AccountAchievements> accountAchievements;

	private List<String> accountBank;

	private List<Integer> accountDyes;

	private List<AccountInventory> accountInventory;

	private List<AccountMaterials> accountMaterials;

	private List<Integer> accountMinis;

	private List<Integer> accountSkins;

	private List<Integer> accountTitles;

	private List<AccountWallet> accountWallet;

	private List<Integer> achievements;

	private List<Integer> achievementCategories;

	private List<String> achievementGroups;

	private List<String> characters;

	private List<Integer> commerceListings;

	private List<Integer> commercePrices;

	private List<Object> commerceCurrentBuyTransactions; //TODO: GW-0003 

	private List<CommerceCurrentSellTransactions> commerceCurrentSellTransactions;

	private List<CommercePastBuyTransactions> commercePastBuyTransactions;

	private List<CommercePastSellTransactions> commercePastSellTransactions;

	private List<String> pvpGames;

	private List<Integer> pvpAmulets;

	private List<String> pvpSeasons;

	//Getters and setters

	public List<AccountAchievements> getAccountAchievements() {
		return this.accountAchievements;
	}

	public void setAccountAchievements(List<AccountAchievements> val) {
		this.accountAchievements = val;
	}

	public List<String> getAccountBank() {
		return this.accountBank;
	}

	public void setAccountBank(List<String> val) {
		this.accountBank = val;
	}

	public List<Integer> getAccountDyes() {
		return this.accountDyes;
	}

	public void setAccountDyes(List<Integer> val) {
		this.accountDyes = val;
	}

	public List<AccountInventory> getAccountInventory() {
		return this.accountInventory;
	}

	public void setAccountInventory(List<AccountInventory> val) {
		this.accountInventory = val;
	}

	public List<AccountMaterials> getAccountMaterials() {
		return this.accountMaterials;
	}

	public void setAccountMaterials(List<AccountMaterials> val) {
		this.accountMaterials = val;
	}

	public List<Integer> getAccountMinis() {
		return this.accountMinis;
	}

	public void setAccountMinis(List<Integer> val) {
		this.accountMinis = val;
	}

	public List<Integer> getAccountSkins() {
		return this.accountSkins;
	}

	public void setAccountSkins(List<Integer> val) {
		this.accountSkins = val;
	}

	public List<Integer> getAccountTitles() {
		return this.accountTitles;
	}

	public void setAccountTitles(List<Integer> val) {
		this.accountTitles = val;
	}

	public List<AccountWallet> getAccountWallet() {
		return this.accountWallet;
	}

	public void setAccountWallet(List<AccountWallet> val) {
		this.accountWallet = val;
	}

	public List<Integer> getAchievements() {
		return this.achievements;
	}

	public void setAchievements(List<Integer> val) {
		this.achievements = val;
	}

	public List<Integer> getAchievementCategories() {
		return this.achievementCategories;
	}

	public void setAchievementCategories(List<Integer> val) {
		this.achievementCategories = val;
	}

	public List<String> getAchievementGroups() {
		return this.achievementGroups;
	}

	public void setAchievementGroups(List<String> val) {
		this.achievementGroups = val;
	}

	public List<String> getCharacters() {
		return this.characters;
	}

	public void setCharacters(List<String> val) {
		this.characters = val;
	}

	public List<Integer> getCommerceListings() {
		return this.commerceListings;
	}

	public void setCommerceListings(List<Integer> val) {
		this.commerceListings = val;
	}

	public List<Integer> getCommercePrices() {
		return this.commercePrices;
	}

	public void setCommercePrices(List<Integer> val) {
		this.commercePrices = val;
	}

	public List<Object> getCommerceCurrentBuyTransactions() {
		return this.commerceCurrentBuyTransactions;
	}

	public void setCommerceCurrentBuyTransactions(List<Object> val) {
		this.commerceCurrentBuyTransactions = val;
	}

	public List<CommerceCurrentSellTransactions> getCommerceCurrentSellTransactions() {
		return this.commerceCurrentSellTransactions;
	}

	public void setCommerceCurrentSellTransactions(List<CommerceCurrentSellTransactions> val) {
		this.commerceCurrentSellTransactions = val;
	}

	public List<CommercePastBuyTransactions> getCommercePastBuyTransactions() {
		return this.commercePastBuyTransactions;
	}

	public void setCommercePastBuyTransactions(List<CommercePastBuyTransactions> val) {
		this.commercePastBuyTransactions = val;
	}

	public List<CommercePastSellTransactions> getCommercePastSellTransactions() {
		return this.commercePastSellTransactions;
	}

	public void setCommercePastSellTransactions(List<CommercePastSellTransactions> val) {
		this.commercePastSellTransactions = val;
	}

	public List<String> getPvpGames() {
		return this.pvpGames;
	}

	public void setPvpGames(List<String> val) {
		this.pvpGames = val;
	}

	public List<Integer> getPvpAmulets() {
		return this.pvpAmulets;
	}

	public void setPvpAmulets(List<Integer> val) {
		this.pvpAmulets = val;
	}

	public List<String> getPvpSeasons() {
		return this.pvpSeasons;
	}

	public void setPvpSeasons(List<String> val) {
		this.pvpSeasons = val;
	}

	public GeneratedJsonArrays() {
		this.accountAchievements = new ArrayList<AccountAchievements>();
		this.accountBank = new ArrayList<String>();
		this.accountDyes = new ArrayList<Integer>();
		this.accountInventory = new ArrayList<AccountInventory>();
		this.accountMaterials = new ArrayList<AccountMaterials>();
		this.accountMinis = new ArrayList<Integer>();
		this.accountSkins = new ArrayList<Integer>();
		this.accountTitles = new ArrayList<Integer>();
		this.accountWallet = new ArrayList<AccountWallet>();
		this.achievements = new ArrayList<Integer>();
		this.achievementCategories = new ArrayList<Integer>();
		this.achievementGroups = new ArrayList<String>();
		this.characters = new ArrayList<String>();
		this.commerceListings = new ArrayList<Integer>();
		this.commercePrices = new ArrayList<Integer>();
		this.commerceCurrentBuyTransactions = new ArrayList<Object>();
		this.commerceCurrentSellTransactions = new ArrayList<CommerceCurrentSellTransactions>();
		this.commercePastBuyTransactions = new ArrayList<CommercePastBuyTransactions>();
		this.commercePastSellTransactions = new ArrayList<CommercePastSellTransactions>();
		this.pvpGames = new ArrayList<String>();
		this.pvpAmulets = new ArrayList<Integer>();
		this.pvpSeasons = new ArrayList<String>();
	}

}
