package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ItemDetailsInfixUpgradeAttributes extends JsonModelFactoryMaster {

	private Integer modifier;

	private String attribute;

	//Getters and setters

	public Integer getModifier() {
		return this.modifier;
	}

	public void setModifier(Integer val) {
		this.modifier = val;
	}

	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String val) {
		this.attribute = val;
	}

	public ItemDetailsInfixUpgradeAttributes() {
	}

}
