package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/itemstats/149
 */
public class ItemStats extends JsonModelFactoryMaster {

	private String name;

	private ItemStatsAttributes itemStatsAttributes;

	private Integer id;

	//Getters and setters

	public String getName() {
		return this.name;
	}

	public void setName(String val) {
		this.name = val;
	}

	public ItemStatsAttributes getItemStatsAttributes() {
		return this.itemStatsAttributes;
	}

	public void setItemStatsAttributes(ItemStatsAttributes val) {
		this.itemStatsAttributes = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public ItemStats() {
	}

}
