package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/itemstats/149
 */
public class ItemStats extends JsonModelFactoryMaster {

	private String name;

	private ItemStatsAttributes itemStatsAttributes;

	private Integer id;

}
