package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ItemDetails extends JsonModelFactoryMaster {

	private ItemDetailsInfixUpgrade itemDetailsInfixUpgrade;

	private String weightClass;

	private String secondarySuffixItemId;

	private Integer defense;

	private Integer suffixItemId;

	private List<Object> infusionSlots; //TODO: GW-0001 

	private String type;

}
