package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/items/1994
 */
public class Item extends JsonModelFactoryMaster {

	private Integer vendorValue;

	private Integer level;

	private Integer defaultSkin;

	private List<String> flags;

	private String icon;

	private String description;

	private List<Object> restrictions; //TODO: GW-0001 

	private List<String> gameTypes;

	private String type;

	private String chatLink;

	private String name;

	private ItemDetails itemDetails;

	private Integer id;

	private String rarity;

}
