package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/legends/Legend2
 */
public class Legend extends JsonModelFactoryMaster {

	private Integer elite;

	private Integer swap;

	private Integer heal;

	private String id;

	private List<Integer> utilities;

}
