package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/maps/15
 */
public class Map extends JsonModelFactoryMaster {

	private String continentName;

	private Integer defaultFloor;

	private Integer continentId;

	private Integer maxLevel;

	private String name;

	private Integer regionId;

	private String regionName;

	private Integer id;

	private Integer minLevel;

}
