package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/minis/333
 */
public class Mini extends JsonModelFactoryMaster {

	private String unlock;

	private Integer itemId;

	private String name;

	private String icon;

	private Integer id;

	private Integer order;

}
