package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/pets/33
 */
public class Pet extends JsonModelFactoryMaster {

	private String name;

	private String icon;

	private String description;

	private Integer id;

}
