package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/professions/Guardian
 */
public class Profession extends JsonModelFactoryMaster {

	private String iconBig;

	private String name;

	private String icon;

	private String id;

	private ProfessionWeapons professionWeapons;

}
