package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsHammer extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsHammerSkills> skills;

	//Getters and setters

	public List<ProfessionWeaponsHammerSkills> getSkills() {
		return this.skills;
	}

	public void setSkills(List<ProfessionWeaponsHammerSkills> val) {
		this.skills = val;
	}

	public ProfessionWeaponsHammer() {
		this.skills = new ArrayList<ProfessionWeaponsHammerSkills>();
	}

}
