package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionTraining extends JsonModelFactoryMaster {

	private String name;

	private Integer id;

	private String category;

	private List<ProfessionTrainingTrack> professionTrainingTrack;

}
