package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsGreatsword extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsGreatswordSkills> professionWeaponsGreatswordSkills;

	//Getters and setters

	public List<ProfessionWeaponsGreatswordSkills> getProfessionWeaponsGreatswordSkills() {
		return this.professionWeaponsGreatswordSkills;
	}

	public void setProfessionWeaponsGreatswordSkills(List<ProfessionWeaponsGreatswordSkills> val) {
		this.professionWeaponsGreatswordSkills = val;
	}

	public ProfessionWeaponsGreatsword() {
		this.professionWeaponsGreatswordSkills = new ArrayList<ProfessionWeaponsGreatswordSkills>();
	}

}
