package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsSpear extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsSpearSkills> professionWeaponsSpearSkills;

	//Getters and setters

	public List<ProfessionWeaponsSpearSkills> getProfessionWeaponsSpearSkills() {
		return this.professionWeaponsSpearSkills;
	}

	public void setProfessionWeaponsSpearSkills(List<ProfessionWeaponsSpearSkills> val) {
		this.professionWeaponsSpearSkills = val;
	}

	public ProfessionWeaponsSpear() {
		this.professionWeaponsSpearSkills = new ArrayList<ProfessionWeaponsSpearSkills>();
	}

}
