package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeapons extends JsonModelFactoryMaster {

	private ProfessionWeaponsHammer Hammer;

	private ProfessionWeaponsMace Mace;

	private ProfessionWeaponsShield Shield;

	private ProfessionWeaponsSword Sword;

	private ProfessionWeaponsFocus Focus;

	private ProfessionWeaponsStaff Staff;

	private ProfessionWeaponsTrident Trident;

	private ProfessionWeaponsGreatsword Greatsword;

	private ProfessionWeaponsScepter Scepter;

	private ProfessionWeaponsSpear Spear;

	private ProfessionWeaponsLongbow Longbow;

	private ProfessionWeaponsTorch Torch;

	//Getters and setters

	public ProfessionWeaponsHammer getHammer() {
		return this.Hammer;
	}

	public void setHammer(ProfessionWeaponsHammer val) {
		this.Hammer = val;
	}

	public ProfessionWeaponsMace getMace() {
		return this.Mace;
	}

	public void setMace(ProfessionWeaponsMace val) {
		this.Mace = val;
	}

	public ProfessionWeaponsShield getShield() {
		return this.Shield;
	}

	public void setShield(ProfessionWeaponsShield val) {
		this.Shield = val;
	}

	public ProfessionWeaponsSword getSword() {
		return this.Sword;
	}

	public void setSword(ProfessionWeaponsSword val) {
		this.Sword = val;
	}

	public ProfessionWeaponsFocus getFocus() {
		return this.Focus;
	}

	public void setFocus(ProfessionWeaponsFocus val) {
		this.Focus = val;
	}

	public ProfessionWeaponsStaff getStaff() {
		return this.Staff;
	}

	public void setStaff(ProfessionWeaponsStaff val) {
		this.Staff = val;
	}

	public ProfessionWeaponsTrident getTrident() {
		return this.Trident;
	}

	public void setTrident(ProfessionWeaponsTrident val) {
		this.Trident = val;
	}

	public ProfessionWeaponsGreatsword getGreatsword() {
		return this.Greatsword;
	}

	public void setGreatsword(ProfessionWeaponsGreatsword val) {
		this.Greatsword = val;
	}

	public ProfessionWeaponsScepter getScepter() {
		return this.Scepter;
	}

	public void setScepter(ProfessionWeaponsScepter val) {
		this.Scepter = val;
	}

	public ProfessionWeaponsSpear getSpear() {
		return this.Spear;
	}

	public void setSpear(ProfessionWeaponsSpear val) {
		this.Spear = val;
	}

	public ProfessionWeaponsLongbow getLongbow() {
		return this.Longbow;
	}

	public void setLongbow(ProfessionWeaponsLongbow val) {
		this.Longbow = val;
	}

	public ProfessionWeaponsTorch getTorch() {
		return this.Torch;
	}

	public void setTorch(ProfessionWeaponsTorch val) {
		this.Torch = val;
	}

	public ProfessionWeapons() {
	}

}
