package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsTorch extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsTorchSkills> professionWeaponsTorchSkills;

	//Getters and setters

	public List<ProfessionWeaponsTorchSkills> getProfessionWeaponsTorchSkills() {
		return this.professionWeaponsTorchSkills;
	}

	public void setProfessionWeaponsTorchSkills(List<ProfessionWeaponsTorchSkills> val) {
		this.professionWeaponsTorchSkills = val;
	}

	public ProfessionWeaponsTorch() {
		this.professionWeaponsTorchSkills = new ArrayList<ProfessionWeaponsTorchSkills>();
	}

}
