package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsTorch extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsTorchSkills> skills;

	//Getters and setters

	public List<ProfessionWeaponsTorchSkills> getSkills() {
		return this.skills;
	}

	public void setSkills(List<ProfessionWeaponsTorchSkills> val) {
		this.skills = val;
	}

	public ProfessionWeaponsTorch() {
		this.skills = new ArrayList<ProfessionWeaponsTorchSkills>();
	}

}
