package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsScepter extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsScepterSkills> professionWeaponsScepterSkills;

	//Getters and setters

	public List<ProfessionWeaponsScepterSkills> getProfessionWeaponsScepterSkills() {
		return this.professionWeaponsScepterSkills;
	}

	public void setProfessionWeaponsScepterSkills(List<ProfessionWeaponsScepterSkills> val) {
		this.professionWeaponsScepterSkills = val;
	}

	public ProfessionWeaponsScepter() {
		this.professionWeaponsScepterSkills = new ArrayList<ProfessionWeaponsScepterSkills>();
	}

}
