package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeapons extends JsonModelFactoryMaster {

	private ProfessionWeaponsHammer professionWeaponsHammer;

	private ProfessionWeaponsMace professionWeaponsMace;

	private ProfessionWeaponsShield professionWeaponsShield;

	private ProfessionWeaponsSword professionWeaponsSword;

	private ProfessionWeaponsFocus professionWeaponsFocus;

	private ProfessionWeaponsStaff professionWeaponsStaff;

	private ProfessionWeaponsTrident professionWeaponsTrident;

	private ProfessionWeaponsGreatsword professionWeaponsGreatsword;

	private ProfessionWeaponsScepter professionWeaponsScepter;

	private ProfessionWeaponsSpear professionWeaponsSpear;

	private ProfessionWeaponsLongbow professionWeaponsLongbow;

	private ProfessionWeaponsTorch professionWeaponsTorch;

}
