package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsShield extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsShieldSkills> professionWeaponsShieldSkills;

	//Getters and setters

	public List<ProfessionWeaponsShieldSkills> getProfessionWeaponsShieldSkills() {
		return this.professionWeaponsShieldSkills;
	}

	public void setProfessionWeaponsShieldSkills(List<ProfessionWeaponsShieldSkills> val) {
		this.professionWeaponsShieldSkills = val;
	}

	public ProfessionWeaponsShield() {
		this.professionWeaponsShieldSkills = new ArrayList<ProfessionWeaponsShieldSkills>();
	}

}
