package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsStaff extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsStaffSkills> skills;

	//Getters and setters

	public List<ProfessionWeaponsStaffSkills> getSkills() {
		return this.skills;
	}

	public void setSkills(List<ProfessionWeaponsStaffSkills> val) {
		this.skills = val;
	}

	public ProfessionWeaponsStaff() {
		this.skills = new ArrayList<ProfessionWeaponsStaffSkills>();
	}

}
