package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsTrident extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsTridentSkills> professionWeaponsTridentSkills;

	//Getters and setters

	public List<ProfessionWeaponsTridentSkills> getProfessionWeaponsTridentSkills() {
		return this.professionWeaponsTridentSkills;
	}

	public void setProfessionWeaponsTridentSkills(List<ProfessionWeaponsTridentSkills> val) {
		this.professionWeaponsTridentSkills = val;
	}

	public ProfessionWeaponsTrident() {
		this.professionWeaponsTridentSkills = new ArrayList<ProfessionWeaponsTridentSkills>();
	}

}
