package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsStaff extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsStaffSkills> professionWeaponsStaffSkills;

	//Getters and setters

	public List<ProfessionWeaponsStaffSkills> getProfessionWeaponsStaffSkills() {
		return this.professionWeaponsStaffSkills;
	}

	public void setProfessionWeaponsStaffSkills(List<ProfessionWeaponsStaffSkills> val) {
		this.professionWeaponsStaffSkills = val;
	}

	public ProfessionWeaponsStaff() {
		this.professionWeaponsStaffSkills = new ArrayList<ProfessionWeaponsStaffSkills>();
	}

}
