package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsMace extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsMaceSkills> professionWeaponsMaceSkills;

	//Getters and setters

	public List<ProfessionWeaponsMaceSkills> getProfessionWeaponsMaceSkills() {
		return this.professionWeaponsMaceSkills;
	}

	public void setProfessionWeaponsMaceSkills(List<ProfessionWeaponsMaceSkills> val) {
		this.professionWeaponsMaceSkills = val;
	}

	public ProfessionWeaponsMace() {
		this.professionWeaponsMaceSkills = new ArrayList<ProfessionWeaponsMaceSkills>();
	}

}
