package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsHammer extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsHammerSkills> professionWeaponsHammerSkills;

	//Getters and setters

	public List<ProfessionWeaponsHammerSkills> getProfessionWeaponsHammerSkills() {
		return this.professionWeaponsHammerSkills;
	}

	public void setProfessionWeaponsHammerSkills(List<ProfessionWeaponsHammerSkills> val) {
		this.professionWeaponsHammerSkills = val;
	}

	public ProfessionWeaponsHammer() {
		this.professionWeaponsHammerSkills = new ArrayList<ProfessionWeaponsHammerSkills>();
	}

}
