package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class ProfessionWeaponsLongbow extends JsonModelFactoryMaster {

	private List<ProfessionWeaponsLongbowSkills> professionWeaponsLongbowSkills;

	private Integer specialization;

	//Getters and setters

	public List<ProfessionWeaponsLongbowSkills> getProfessionWeaponsLongbowSkills() {
		return this.professionWeaponsLongbowSkills;
	}

	public void setProfessionWeaponsLongbowSkills(List<ProfessionWeaponsLongbowSkills> val) {
		this.professionWeaponsLongbowSkills = val;
	}

	public Integer getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(Integer val) {
		this.specialization = val;
	}

	public ProfessionWeaponsLongbow() {
		this.professionWeaponsLongbowSkills = new ArrayList<ProfessionWeaponsLongbowSkills>();
	}

}
