package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpAmuletAttributes extends JsonModelFactoryMaster {

	private Integer Toughness;

	private Integer Precision;

	private Integer Power;

}
