package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/pvp/amulets/12
 */
public class PvpAmulet extends JsonModelFactoryMaster {

	private String name;

	private String icon;

	private PvpAmuletAttributes pvpAmuletAttributes;

	private Integer id;

}
