package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/pvp/amulets/12
 */
public class PvpAmulet extends JsonModelFactoryMaster {

	private String name;

	private String icon;

	private PvpAmuletAttributes pvpAmuletAttributes;

	private Integer id;

	//Getters and setters

	public String getName() {
		return this.name;
	}

	public void setName(String val) {
		this.name = val;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String val) {
		this.icon = val;
	}

	public PvpAmuletAttributes getPvpAmuletAttributes() {
		return this.pvpAmuletAttributes;
	}

	public void setPvpAmuletAttributes(PvpAmuletAttributes val) {
		this.pvpAmuletAttributes = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public PvpAmulet() {
	}

}
