package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/pvp/games/10801E29-4CF1-4F7E-82B6-FC1F8A90855D?access_token=79D451B9-26E6-6943-BDA6-AC9D05EE563DA640C336-0F50-4875-8350-23E6C642A0F1
 */
public class PvpGame extends JsonModelFactoryMaster {

	private String result;

	private String profession;

	private Integer mapId;

	private PvpGameScores pvpGameScores;

	private String ratingType;

	private String ended;

	private String season;

	private String started;

	private String id;

	private String team;

}
