package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/pvp/seasons/44B85826-B5ED-4890-8C77-82DDF9F2CF2B
 */
public class PvpSeason extends JsonModelFactoryMaster {

	private String name;

	private String start;

	private Boolean active;

	private String end;

	private String id;

	private List<PvpSeasonDivisions> divisions;

	//Getters and setters

	public String getName() {
		return this.name;
	}

	public void setName(String val) {
		this.name = val;
	}

	public String getStart() {
		return this.start;
	}

	public void setStart(String val) {
		this.start = val;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean val) {
		this.active = val;
	}

	public String getEnd() {
		return this.end;
	}

	public void setEnd(String val) {
		this.end = val;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String val) {
		this.id = val;
	}

	public List<PvpSeasonDivisions> getDivisions() {
		return this.divisions;
	}

	public void setDivisions(List<PvpSeasonDivisions> val) {
		this.divisions = val;
	}

	public PvpSeason() {
		this.divisions = new ArrayList<PvpSeasonDivisions>();
	}

}
