package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/pvp/seasons/44B85826-B5ED-4890-8C77-82DDF9F2CF2B
 */
public class PvpSeason extends JsonModelFactoryMaster {

	private String name;

	private String start;

	private Boolean active;

	private String end;

	private String id;

	private List<PvpSeasonDivisions> pvpSeasonDivisions;

}
