package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpStatsLadders extends JsonModelFactoryMaster {

	private PvpStatsLaddersSoloarenarated pvpStatsLaddersSoloarenarated;

	private PvpStatsLaddersTeamarenarated pvpStatsLaddersTeamarenarated;

	private PvpStatsLaddersRanked pvpStatsLaddersRanked;

	private PvpStatsLaddersNone pvpStatsLaddersNone;

	private PvpStatsLaddersUnranked pvpStatsLaddersUnranked;

}
