package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpSeasonDivisions extends JsonModelFactoryMaster {

	private List<PvpSeasonDivisionsTiers> pvpSeasonDivisionsTiers;

	private String name;

	private List<Object> flags; //TODO: GW-0001 

	private String largeIcon;

	private String smallIcon;

	private String pipIcon;

}
