package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpStandings extends JsonModelFactoryMaster {

	private PvpStandingsCurrent pvpStandingsCurrent;

	private PvpStandingsBest pvpStandingsBest;

	private String seasonId;

	//Getters and setters

	public PvpStandingsCurrent getPvpStandingsCurrent() {
		return this.pvpStandingsCurrent;
	}

	public void setPvpStandingsCurrent(PvpStandingsCurrent val) {
		this.pvpStandingsCurrent = val;
	}

	public PvpStandingsBest getPvpStandingsBest() {
		return this.pvpStandingsBest;
	}

	public void setPvpStandingsBest(PvpStandingsBest val) {
		this.pvpStandingsBest = val;
	}

	public String getSeasonId() {
		return this.seasonId;
	}

	public void setSeasonId(String val) {
		this.seasonId = val;
	}

	public PvpStandings() {
	}

}
