package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpStatsProfessionsNecromancer extends JsonModelFactoryMaster {

	private Integer wins;

	private Integer forfeits;

	private Integer desertions;

	private Integer byes;

	private Integer losses;

	//Getters and setters

	public Integer getWins() {
		return this.wins;
	}

	public void setWins(Integer val) {
		this.wins = val;
	}

	public Integer getForfeits() {
		return this.forfeits;
	}

	public void setForfeits(Integer val) {
		this.forfeits = val;
	}

	public Integer getDesertions() {
		return this.desertions;
	}

	public void setDesertions(Integer val) {
		this.desertions = val;
	}

	public Integer getByes() {
		return this.byes;
	}

	public void setByes(Integer val) {
		this.byes = val;
	}

	public Integer getLosses() {
		return this.losses;
	}

	public void setLosses(Integer val) {
		this.losses = val;
	}

	public PvpStatsProfessionsNecromancer() {
	}

}
