package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpStandings extends JsonModelFactoryMaster {

	private PvpStandingsCurrent current;

	private PvpStandingsBest best;

	private String seasonId;

	//Getters and setters

	public PvpStandingsCurrent getCurrent() {
		return this.current;
	}

	public void setCurrent(PvpStandingsCurrent val) {
		this.current = val;
	}

	public PvpStandingsBest getBest() {
		return this.best;
	}

	public void setBest(PvpStandingsBest val) {
		this.best = val;
	}

	public String getSeasonId() {
		return this.seasonId;
	}

	public void setSeasonId(String val) {
		this.seasonId = val;
	}

	public PvpStandings() {
	}

}
