package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpStatsLadders extends JsonModelFactoryMaster {

	private PvpStatsLaddersSoloarenarated soloarenarated;

	private PvpStatsLaddersTeamarenarated teamarenarated;

	private PvpStatsLaddersRanked ranked;

	private PvpStatsLaddersNone none;

	private PvpStatsLaddersUnranked unranked;

	//Getters and setters

	public PvpStatsLaddersSoloarenarated getSoloarenarated() {
		return this.soloarenarated;
	}

	public void setSoloarenarated(PvpStatsLaddersSoloarenarated val) {
		this.soloarenarated = val;
	}

	public PvpStatsLaddersTeamarenarated getTeamarenarated() {
		return this.teamarenarated;
	}

	public void setTeamarenarated(PvpStatsLaddersTeamarenarated val) {
		this.teamarenarated = val;
	}

	public PvpStatsLaddersRanked getRanked() {
		return this.ranked;
	}

	public void setRanked(PvpStatsLaddersRanked val) {
		this.ranked = val;
	}

	public PvpStatsLaddersNone getNone() {
		return this.none;
	}

	public void setNone(PvpStatsLaddersNone val) {
		this.none = val;
	}

	public PvpStatsLaddersUnranked getUnranked() {
		return this.unranked;
	}

	public void setUnranked(PvpStatsLaddersUnranked val) {
		this.unranked = val;
	}

	public PvpStatsLadders() {
	}

}
