package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpStatsProfessions extends JsonModelFactoryMaster {

	private PvpStatsProfessionsRevenant pvpStatsProfessionsRevenant;

	private PvpStatsProfessionsThief pvpStatsProfessionsThief;

	private PvpStatsProfessionsWarrior pvpStatsProfessionsWarrior;

	private PvpStatsProfessionsNecromancer pvpStatsProfessionsNecromancer;

	private PvpStatsProfessionsRanger pvpStatsProfessionsRanger;

	private PvpStatsProfessionsMesmer pvpStatsProfessionsMesmer;

	private PvpStatsProfessionsGuardian pvpStatsProfessionsGuardian;

	private PvpStatsProfessionsElementalist pvpStatsProfessionsElementalist;

	private PvpStatsProfessionsEngineer pvpStatsProfessionsEngineer;

}
