package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpStatsProfessionsElementalist extends JsonModelFactoryMaster {

	private Integer wins;

	private Integer forfeits;

	private Integer desertions;

	private Integer byes;

	private Integer losses;

}
