package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class PvpStandingsBest extends JsonModelFactoryMaster {

	private Integer division;

	private Integer repeats;

	private Integer tier;

	private Integer totalPoints;

	private Integer points;

	//Getters and setters

	public Integer getDivision() {
		return this.division;
	}

	public void setDivision(Integer val) {
		this.division = val;
	}

	public Integer getRepeats() {
		return this.repeats;
	}

	public void setRepeats(Integer val) {
		this.repeats = val;
	}

	public Integer getTier() {
		return this.tier;
	}

	public void setTier(Integer val) {
		this.tier = val;
	}

	public Integer getTotalPoints() {
		return this.totalPoints;
	}

	public void setTotalPoints(Integer val) {
		this.totalPoints = val;
	}

	public Integer getPoints() {
		return this.points;
	}

	public void setPoints(Integer val) {
		this.points = val;
	}

	public PvpStandingsBest() {
	}

}
