package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/quaggans/404
 */
public class Quaggan extends JsonModelFactoryMaster {

	private Integer id;

	private String url;

	//Getters and setters

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String val) {
		this.url = val;
	}

	public Quaggan() {
	}

}
