package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/recipes/1994
 */
public class Recipe extends JsonModelFactoryMaster {

	private Integer timeToCraftMs;

	private List<String> disciplines;

	private Integer outputItemId;

	private Integer minRating;

	private List<Object> flags; //TODO: GW-0001 

	private Integer outputItemCount;

	private List<RecipeIngredients> recipeIngredients;

	private Integer id;

	private String type;

	private String chatLink;

}
