package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/skills/5486
 */
public class Skill extends JsonModelFactoryMaster {

	private String attunement;

	private String name;

	private String icon;

	private List<String> professions;

	private List<Object> flags; //TODO: GW-0001 

	private String description;

	private String weaponType;

	private String slot;

	private Integer id;

	private String type;

	private String chatLink;

	private List<SkillFacts> skillFacts;

}
