package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/skins/1994
 */
public class Skin extends JsonModelFactoryMaster {

	private String name;

	private List<String> flags;

	private String icon;

	private List<Object> restrictions; //TODO: GW-0001 

	private SkinDetails skinDetails;

	private Integer id;

	private String type;

	private String rarity;

}
