package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/specializations/37
 */
public class Specialization extends JsonModelFactoryMaster {

	private String profession;

	private Boolean elite;

	private String background;

	private String name;

	private String icon;

	private Integer id;

}
