package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/achievements/daily/tomorrow
 */
public class TomorrowDailyAchievements extends JsonModelFactoryMaster {

	private List<Object> special; //TODO: GW-0001 

	private List<TomorrowDailyAchievementsWvw> tomorrowDailyAchievementsWvw;

	private List<TomorrowDailyAchievementsPvp> tomorrowDailyAchievementsPvp;

	private List<TomorrowDailyAchievementsPve> tomorrowDailyAchievementsPve;

	//Getters and setters

	public List<Object> getSpecial() {
		return this.special;
	}

	public void setSpecial(List<Object> val) {
		this.special = val;
	}

	public List<TomorrowDailyAchievementsWvw> getTomorrowDailyAchievementsWvw() {
		return this.tomorrowDailyAchievementsWvw;
	}

	public void setTomorrowDailyAchievementsWvw(List<TomorrowDailyAchievementsWvw> val) {
		this.tomorrowDailyAchievementsWvw = val;
	}

	public List<TomorrowDailyAchievementsPvp> getTomorrowDailyAchievementsPvp() {
		return this.tomorrowDailyAchievementsPvp;
	}

	public void setTomorrowDailyAchievementsPvp(List<TomorrowDailyAchievementsPvp> val) {
		this.tomorrowDailyAchievementsPvp = val;
	}

	public List<TomorrowDailyAchievementsPve> getTomorrowDailyAchievementsPve() {
		return this.tomorrowDailyAchievementsPve;
	}

	public void setTomorrowDailyAchievementsPve(List<TomorrowDailyAchievementsPve> val) {
		this.tomorrowDailyAchievementsPve = val;
	}

	public TomorrowDailyAchievements() {
		this.special = new ArrayList<Object>();
		this.tomorrowDailyAchievementsWvw = new ArrayList<TomorrowDailyAchievementsWvw>();
		this.tomorrowDailyAchievementsPvp = new ArrayList<TomorrowDailyAchievementsPvp>();
		this.tomorrowDailyAchievementsPve = new ArrayList<TomorrowDailyAchievementsPve>();
	}

}
