package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/achievements/daily/tomorrow
 */
public class TomorrowDailyAchievements extends JsonModelFactoryMaster {

	private List<Object> special; //TODO: GW-0001 

	private List<TomorrowDailyAchievementsWvw> wvw;

	private List<TomorrowDailyAchievementsPvp> pvp;

	private List<TomorrowDailyAchievementsPve> pve;

	//Getters and setters

	public List<Object> getSpecial() {
		return this.special;
	}

	public void setSpecial(List<Object> val) {
		this.special = val;
	}

	public List<TomorrowDailyAchievementsWvw> getWvw() {
		return this.wvw;
	}

	public void setWvw(List<TomorrowDailyAchievementsWvw> val) {
		this.wvw = val;
	}

	public List<TomorrowDailyAchievementsPvp> getPvp() {
		return this.pvp;
	}

	public void setPvp(List<TomorrowDailyAchievementsPvp> val) {
		this.pvp = val;
	}

	public List<TomorrowDailyAchievementsPve> getPve() {
		return this.pve;
	}

	public void setPve(List<TomorrowDailyAchievementsPve> val) {
		this.pve = val;
	}

	public TomorrowDailyAchievements() {
		this.special = new ArrayList<Object>();
		this.wvw = new ArrayList<TomorrowDailyAchievementsWvw>();
		this.pvp = new ArrayList<TomorrowDailyAchievementsPvp>();
		this.pve = new ArrayList<TomorrowDailyAchievementsPve>();
	}

}
