package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class TomorrowDailyAchievementsPve extends JsonModelFactoryMaster {

	private TomorrowDailyAchievementsPveLevel tomorrowDailyAchievementsPveLevel;

	private Integer id;

	private List<String> requiredAccess;

	//Getters and setters

	public TomorrowDailyAchievementsPveLevel getTomorrowDailyAchievementsPveLevel() {
		return this.tomorrowDailyAchievementsPveLevel;
	}

	public void setTomorrowDailyAchievementsPveLevel(TomorrowDailyAchievementsPveLevel val) {
		this.tomorrowDailyAchievementsPveLevel = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public List<String> getRequiredAccess() {
		return this.requiredAccess;
	}

	public void setRequiredAccess(List<String> val) {
		this.requiredAccess = val;
	}

	public TomorrowDailyAchievementsPve() {
		this.requiredAccess = new ArrayList<String>();
	}

}
