package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class TraitFacts extends JsonModelFactoryMaster {

	private String icon;

	private String text;

	private String type;

	private Integer percent;

	private Integer value;

	private String target;

}
