package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/traits/214
 */
public class Trait extends JsonModelFactoryMaster {

	private Integer tier;

	private String name;

	private String icon;

	private String description;

	private Integer specialization;

	private Integer id;

	private String slot;

	private Integer order;

}
