package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class WvwMatchMaps extends JsonModelFactoryMaster {

	private WvwMatchMapsKills wvwMatchMapsKills;

	private WvwMatchMapsScores wvwMatchMapsScores;

	private List<WvwMatchMapsObjectives> wvwMatchMapsObjectives;

	private Integer id;

	private String type;

	private List<WvwMatchMapsBonuses> wvwMatchMapsBonuses;

	private WvwMatchMapsDeaths wvwMatchMapsDeaths;

}
