package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class WvwMatchMapsObjectives extends JsonModelFactoryMaster {

	private String owner;

	private String claimedAt;

	private String lastFlipped;

	private String id;

	private String type;

	private String claimedBy;

}
