package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class WvwMatchMapsBonuses extends JsonModelFactoryMaster {

	private String owner;

	private String type;

	//Getters and setters

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String val) {
		this.owner = val;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String val) {
		this.type = val;
	}

	public WvwMatchMapsBonuses() {
	}

}
