package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: null
 */
public class WvwMatchMaps extends JsonModelFactoryMaster {

	private WvwMatchMapsKills kills;

	private WvwMatchMapsScores scores;

	private List<WvwMatchMapsObjectives> objectives;

	private Integer id;

	private String type;

	private List<WvwMatchMapsBonuses> bonuses;

	private WvwMatchMapsDeaths deaths;

	//Getters and setters

	public WvwMatchMapsKills getKills() {
		return this.kills;
	}

	public void setKills(WvwMatchMapsKills val) {
		this.kills = val;
	}

	public WvwMatchMapsScores getScores() {
		return this.scores;
	}

	public void setScores(WvwMatchMapsScores val) {
		this.scores = val;
	}

	public List<WvwMatchMapsObjectives> getObjectives() {
		return this.objectives;
	}

	public void setObjectives(List<WvwMatchMapsObjectives> val) {
		this.objectives = val;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer val) {
		this.id = val;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String val) {
		this.type = val;
	}

	public List<WvwMatchMapsBonuses> getBonuses() {
		return this.bonuses;
	}

	public void setBonuses(List<WvwMatchMapsBonuses> val) {
		this.bonuses = val;
	}

	public WvwMatchMapsDeaths getDeaths() {
		return this.deaths;
	}

	public void setDeaths(WvwMatchMapsDeaths val) {
		this.deaths = val;
	}

	public WvwMatchMaps() {
		this.objectives = new ArrayList<WvwMatchMapsObjectives>();
		this.bonuses = new ArrayList<WvwMatchMapsBonuses>();
	}

}
