package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/wvw/matches/2-1
 */
public class WvwMatch extends JsonModelFactoryMaster {

	private WvwMatchKills wvwMatchKills;

	private String startTime;

	private WvwMatchWorlds wvwMatchWorlds;

	private WvwMatchScores wvwMatchScores;

	private String endTime;

	private String id;

	private WvwMatchAllWorlds wvwMatchAllWorlds;

	private WvwMatchDeaths wvwMatchDeaths;

}
