package rs.edu.viser.json.models;

import java.util.List;
import java.util.ArrayList;

import rs.edu.viser.json.JsonModelFactoryMaster;

/**
 * Class generated by rs.edu.viser.json.generator.ClassFileWriter
 * Generated from: https://api.guildwars2.com/v2/wvw/objectives/1143-117
 */
public class WvwObjective extends JsonModelFactoryMaster {

	private String mapType;

	private Integer sectorId;

	private Integer mapId;

	private String name;

	private String id;

	private String type;

	//Getters and setters

	public String getMapType() {
		return this.mapType;
	}

	public void setMapType(String val) {
		this.mapType = val;
	}

	public Integer getSectorId() {
		return this.sectorId;
	}

	public void setSectorId(Integer val) {
		this.sectorId = val;
	}

	public Integer getMapId() {
		return this.mapId;
	}

	public void setMapId(Integer val) {
		this.mapId = val;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String val) {
		this.name = val;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String val) {
		this.id = val;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String val) {
		this.type = val;
	}

	public WvwObjective() {
	}

}
